# MongoDB local (localhost) - sin Atlas. Perfil: localdb
spring.data.mongodb.uri=mongodb://localhost:27017/submerso_db
jwt.secret=YourSuperSecretKeyForJWTTokenGenerationMustBeAtLeast256BitsLongForHS256Algorithm
